# Generated by Django 5.1.7 on 2025-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collectionrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='ewaste_docs/'),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ewaste_images/'),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ewasteitem',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('home_appliance', 'Home Appliance'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ewasteitem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged'), ('not_working', 'Not Working')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
